site_name: DAPHNE
docs_dir: doc
site_dir: doc_build
theme:
  name: material
  logo: assets/logo_small.png
  favicon: assets/logo_small.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.striphtml
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
repo_url: https://github.com/daphne-eu/daphne
repo_name: daphne-eu/daphne
nav:
  - 'Home':
    - README.md
    - GettingStarted.md
  - 'Users':
    - RunningDaphneLocally.md
    - 'Configuration': Config.md
    - 'DaphneDSL':
      - DaphneDSL/LanguageRef.md
      - DaphneDSL/Builtins.md
      - DaphneDSL/Imports.md
    - 'DaphneLib':
      - DaphneLib/Overview.md
      - DaphneLib/APIRef.md
    - FileMetaDataFormat.md
    - DistributedRuntime.md
    - SchedulingOptions.md
    - 'Tutorials':
      - tutorial/sqlTutorial.md
    - FPGAconfiguration.md
    - MPI-Usage.md
    - Profiling.md
  - 'Developers':
    - development/Contributing.md
    - development/BuildingDaphne.md
    - Deploy.md
    - ReleaseScripts.md
    - BinaryFormat.md
    - development/Logging.md
    - development/ExtendingDistributedRuntime.md
    - development/ExtendingSchedulingKnobs.md
    - development/HandlingPRs.md
    - development/ImplementBuiltinKernel.md
    - development/Profiling.md
    - development/WriteDocs.md
