import os
import subprocess
import numpy as np
import json

# Set paths
dml_file = os.path.abspath("../../../thirdparty/systemds/scripts/builtin/sigmoid.dml")
dml_file_caller = os.path.abspath("../../../thirdparty/systemds/src/test/scripts/functions/builtin/sigmoid.dml")

translator_file = os.path.abspath("../../dml2daph.py")
daph_file = os.path.abspath("../../translated_files/sigmoid.daph")   # is generated by translator
daph_file_caller = os.path.abspath("sigmoid_.daph")

# Generate data
test_matrix = np.random.rand(30, 20)
test_matrix_file_dml = os.path.abspath('data/test_matrix_dml.csv')
test_matrix_file_daph = os.path.abspath('data/test_matrix_daph.csv')

# Save the matrix to a file
np.savetxt(test_matrix_file_dml, test_matrix, delimiter=',')
np.savetxt(test_matrix_file_daph, test_matrix, delimiter=',')

# Create metadata for the test matrix
test_matrix_metadata_dml = {
    "data_type": "matrix",
    "format": "csv",
    "rows": test_matrix.shape[0],
    "cols": test_matrix.shape[1]
}

test_matrix_metadata_daph = {
    "numRows": test_matrix.shape[0],
    "numCols": test_matrix.shape[1],
    "valueType": "f64",
    "numNonZeros": 0
}

# Save metadata to a file
with open(test_matrix_file_dml + ".mtd", 'w') as f:
    json.dump(test_matrix_metadata_dml, f)

with open(test_matrix_file_daph + ".meta", 'w') as f:
    json.dump(test_matrix_metadata_daph, f)

# Run the DML script
dml_output_file = os.path.abspath('output/dml_output.csv')
dml_command = "cd ../../../thirdparty/systemds/target && spark-submit SystemDS.jar -f {} -args {} {}".format(dml_file_caller, test_matrix_file_dml, dml_output_file)
subprocess.call(dml_command, shell=True)

# Load DML results
dml_results = np.loadtxt(dml_output_file, delimiter=' ')

# Translate DML to Daphne
translate_command = "python3 {} {}".format(translator_file, dml_file)
subprocess.call(translate_command, shell=True)

# Run the Daphne script
daphne_output_file = os.path.abspath('output/daphne_output.csv')
daphne_command = "../../../bin/daphne {}".format(daph_file_caller)
subprocess.call(daphne_command, shell=True)

# Load Daphne results
daphne_results = np.loadtxt(daphne_output_file, delimiter=',')

# Compare results
print("Comparison for m_sigmoid: {}".format(np.allclose(dml_results[:,2].reshape(test_matrix.shape[0], test_matrix.shape[1]), daphne_results, atol=1e-08)))

